title: mapping pathways in higher education
author: tobias dalberg
github_username: tdalberg
description: a research project funded by Knut & Alice Wallenberg Foundation
theme: minima

header_pages:
 - activities.md
