title: mapping pathways in higher education
author: tobias dalberg
email: 
twitter_username: tobias_dalberg
github_username: tdalberg
description: 

theme: minimal-mistakes-jekyll

header_pages:
 - research.md
 - activities.md
 - writings.md
