title: mapping pathways in higher education
author: tobias dalberg
email: 
twitter_username: tobias_dalberg
github_username: tdalberg
description: 

theme: minima

header_pages:
 - activities.md
 - writings.md
