title: mapping pathways in higher education
author: tobias dalberg
email: 
twitter_username: tobias_dalberg
github_username: tdalberg
description: 

# theme: minima
remote_theme: "mmistakes/minimal-mistakes@4.22.0"

header_pages:
 - research.md
 - activities.md
 - writings.md
